# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_digest', '0002_auto_20160822_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='submitter',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='quote_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quote_author',
            name='author',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='quote_author',
            name='biography_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
