# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-07 22:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('daily_digest', '0003_auto_20160823_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='date_last_served',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='date last served'),
        ),
    ]
