# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-09 01:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('daily_digest', '0004_quote_date_last_served'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('demo_url', models.URLField(blank=True, null=True)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('date_last_served', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='date last served')),
                ('times_served', models.PositiveSmallIntegerField(default=0)),
                ('votes', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
