# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-09 01:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('daily_digest', '0005_exercise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='pub_date',
        ),
        migrations.AlterField(
            model_name='exercise',
            name='date_last_served',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
